apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-management-ingress
  namespace: prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: vhbj.site
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service: { name: backend-svc, port: { number: 5000 } }
      - path: /
        pathType: Prefix
        backend:
          service: { name: frontend-svc, port: { number: 80 } }
  - host: www.vhbj.site
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service: { name: backend-svc, port: { number: 5000 } }
      - path: /
        pathType: Prefix
        backend:
          service: { name: frontend-svc, port: { number: 80 } }
  tls:
  - hosts: [vhbj.site, www.vhbj.site]
    secretName: vhbj.site-com-tls   # <-- consistent, .com
